[build]
publish = "_site"
command = "rm -rf node_modules && npm install && npm run build"

[build.environment]
NODE_VERSION = "22"

[[plugins]]
package = "netlify-plugin-cache"

[plugins.inputs]
paths = [".cache"]

[[redirects]]
from = "/admin/*"
to = "/admin/index.html"
status = 200
