name: Mastodon Bot

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'

  # Allow manual triggering
  workflow_dispatch:

jobs:
  post-to-mastodon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: mastodon-bot/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: mastodon-bot

      - name: Run bot check
        run: node index.js
        working-directory: mastodon-bot
        env:
          MASTODON_URL: ${{ secrets.MASTODON_URL }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          FEED_URL: https://nightdogs.xyz/feed/feed.xml
          DRY_RUN: false
          POST_LIMIT: 280
          CHECK_INTERVAL: "0 0 * * *"  # This won't be used in GitHub Actions
          AUTHOR_HANDLES: ${{ secrets.AUTHOR_HANDLES }}

      - name: Cache posted items
        uses: actions/cache@v3
        with:
          path: mastodon-bot/posted-items.json
          key: posted-items-${{ github.run_id }}
          restore-keys: |
            posted-items-
